config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#top"
  get "home/about" => "home#about"
  resources :users
  resources :books
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

	belongs_to :user

	validates :title, presence: true
	validates :body, presence: true
	validates :body, length: { maximum: 200 }


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  has_many :books, dependent: :destroy

  validates :name, presence: true
  validates :name, length: { minimum: 2 }
  validates :name, length: { maximum: 20 }
  validates :introduction, length:{ maximum: 50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters, if: :devise_controller?

	def after_sign_in_path_for(resources)
		user_path(current_user) #サインインしているユーザーの取得
	end

	protected
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
		devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
		devise_parameter_sanitizer.permit(:account_update, keys: [:name])
	end


end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  before_action :ensure_correct_user, {only: [:edit, :update]}


  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
    @users = User.all
  end

  def show
    @book = Book.new
    @books = Book.find(params[:id])
  end

  def edit
  	@book = Book.find(params[:id])
  end

  def update
    book = Book.find(params[:id])
    if book.update(book_params)
       flash[:notice] = "successfully"
       redirect_to book_path(book.id)
    else
        flash[:alert] = "error"
        #redirect_to edit_book_path(book.id)
        @book = Book.find(params[:id])
        render 'books/edit'
    end
  end


  def create
  	book = Book.new(book_params)
    book.user_id = current_user.id
    if book.save
      flash[:notice] = "successfully"
      redirect_to book_path(book.id) #新しく作られたidのところに行く
    else
    @user = current_user
    @book = book
    @users = User.all
    @books = Book.all
      render 'books/index'
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
      params.require(:book).permit(:title, :body)
  end

  def ensure_correct_user
  if current_user.id != params[:id].to_i
    flash[:notice] = "権限がありません"
    redirect_to books_path
  end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def top
		
	end

	def about
		
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!

	before_action :ensure_correct_user, {only: [:edit, :update]}

	def index
		@users = User.all
		@user = current_user
		@book = Book.new

	end

	def show
		@user = User.find(params[:id])
		@book = Book.new
		@books = @user.books
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		user = User.find(params[:id])
	 if user.update(user_params)
        flash[:notice] = "successfully"
        redirect_to user_path(user.id)
      	else
      	flash[:alert] = "error"
      	redirect_to user_path(user.id)
      	#@user = User.find(params[:id])
        #render 'users/edit'
     end
	end

	private
	def user_params
      params.require(:user).permit(:name, :profile_image, :introduction)
    end

    def ensure_correct_user
  		if current_user.id != params[:id].to_i
    	flash[:notice] = "権限がありません"
    	redirect_to user_path(current_user)
  		end
  	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<h1>Editing Book</h1>

  <%= form_for(@book) do |f| %>
<% if @book.errors.any? %>
  <div class="form-error">
  <h2><%= @book.errors.count %>errors</h2>
  <ul>
  <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
  </div>
<% end %>

  <p>Title</p>
  <%= f.text_field :title, class: "book_title" %>
  <p>Opinion</p>
  <%= f.text_area :body, class: "book_opinion" %>
  <%= f.submit 'Update book' %>

  <% end %>

  <%= link_to "Show", book_path(@book) %>
  <%= link_to "back", books_path %>
  </div>
</div>

app/views/books/index.html.erb
<%= render 'users/list', user: @user, book: @book %>

<div class="col-xs-9">
<h2>Books</h2>
  <table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
    </tr>
  </thead>

  <tbody>
<% @books.each do |book| %>
    <tr>
      <td>
        <%= link_to user_path(book.user) do %>
        <%= attachment_image_tag book.user, :profile_image, :fill, 100, 100, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg"%>
        <% end %>
      </td>
      <td>
        <%= link_to book.title, book_path(book) %>
      </td>
      <td>
        <%= book.body %>
      </td>
<% end %>
    </tr>
  </tbody>
  </table>
</div>

app/views/books/show.html.erb
<div class="col-xs-3">
    <h2>User info</h2>
    <div class="profile">
      <%= attachment_image_tag @books.user,:profile_image, :fill, 100, 100, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpeg"%>
    </div>
    <table class="table">
    <tbody>
      <tr>
        <th>name</th>
        <th><%= @books.user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= @books.user.introduction %></th>
      </tr>
    </tbody>
    </table>



<div class="row">
<% if @books.user.id == current_user.id %>
  <%= link_to "", edit_user_path(@books.user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_5239"%>
<% else %>
  <%= link_to "", user_path(current_user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_5239"%>
<% end %>
</div>

<h2>New Book</h2>
<%= form_for(@book) do |f| %>
<% if @book.errors.any? %>
  <div class="form-error">
  <h2><%= @book.errors.count %>errors</h2>
  <ul>
  <% @book.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  </div>
<% end %>
  <p>Title</p>
  <%= f.text_field :title, class: "book_title" %>
  <p>Opinion</p>
  <%= f.text_area :body, class: "book_opinion" %>
  <%= f.submit 'create book' %>
<% end %>
</div>

<div class="col-xs-9">
<h2>Books detail</h2>
  <table class="table">
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
        <%= link_to user_path(@books.user) do %>
        <%= attachment_image_tag @books.user, :profile_image, :fill, 100, 100, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpeg" %>
        <% end %>
        <br>
        <%= link_to @books.user.name, user_path(@books.user) %>
      </td>
      <td>
        <%= @books.title %>
      </td>
      <td>
        <%= @books.body %>
      </td>
      <td>
        <% if @books.user_id == current_user.id %>
        <%= link_to "Edit",edit_book_path(@books)%>
        <% end %>
      </td>
      <td>
        <% if @books.user_id == current_user.id %>
        <%= link_to "Destroy",  book_path(@books), method: :delete %>
        <% end %>
      </td>
    </tr>
  </tbody>
  </table>
</div>

app/views/home/about.html.erb
<h1>Welcome to <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>!</h1>

app/views/home/top.html.erb
<div class="row">
  <div class="top-message col-md-offset-3 col-md-6">
    <h1>welcome to <span class="glyphicon glyphicon-book"><strong>Bookers</strong>  !!</span></h1>
          <p>In  <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>, </p>
          <p>you can share and exchange  your opinions , inpressions , and emotions</p>
          <p> about varioius books!</p>

    <div class="btn-wrapper">
      <div class="row">
         <%= link_to "Log in",new_user_session_path, class:"btn btn-info col-xs-10 col-xs-offset-1 sign_in"%>
      </div>
      <div class="row">
        <%= link_to "Sign Up", new_user_registration_path, class:"btn btn-success col-xs-10 col-xs-offset-1 sign_up"%>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav class="nav navbar-nav navbar-left">
      <span>Bookers</span>
    </nav>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Home", user_path(current_user), class: 'glyphicon glyphicon-home home' %> </li>
          <li><%= link_to "Users", users_path, class: "glyphicon glyphicon-user users" %></li>
          <li><%= link_to "Books",books_path, class: "glyphicon glyphicon-book books" %> </li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out logout" %></li>
        <% else %>
          <li><%= link_to "Home", root_path, class: 'glyphicon glyphicon-home home' %></li>
          <li><%= link_to "About", home_about_path, class: "glyphicon glyphicon-link about" %></li>
          <li><%= link_to "sign up", new_user_registration_path, class: "glyphicon glyphicon-edit sign_up" %></li>
          <li><%= link_to"log_in", new_user_session_path, class: "glyphicon glyphicon-log-in sign_in"  %></li>
        <% end %>
      </ul>
    </nav>
  </div>
  </header>


  <div class="body">
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>
    <%= yield %>
    </div>
  </div>

  <footer>
  <div class="container">
    <div class="row">
      <div class="col-xs-3 col-xs-offset-9">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
  </footer>
  </body>
</html>

app/views/users/_list.html.erb
<div class="col-xs-3">
    <h2>User info</h2>
    <div class="profile">
      <%= attachment_image_tag user,:profile_image, :fill, 100, 100, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpeg"%>
    </div>
    <table class="table">
    <tbody>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>
    </tbody>
    </table>



<div class="row">
<% if @user.id == current_user.id %>
  <%= link_to "", edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_5239"%>
<% else %>
  <%= link_to "", user_path(current_user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_5239"%>
<% end %>
</div>

<h2>New Book</h2>
<%= form_for(book) do |f| %>
<% if book.errors.any? %>
  <div class="form-error">
  <h2><%= book.errors.count %>errors</h2>
  <ul>
  <% book.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  </div>
<% end %>
  <p>Title</p>
  <%= f.text_field :title, class: "book_title" %>
  <p>Opinion</p>
  <%= f.text_area :body, class: "book_opinion" %>
  <%= f.submit 'create book' %>
<% end %>
</div>

app/views/users/edit.html.erb
<h2>Use info</h2>

<div class="container">
<%= form_for(@user) do |f| %>

<% if @user.errors.any? %>
  <div class="form-error">
  <h2><%= @user.errors.count %>件のエラーが発生しました。</h2>
  <ul>
  <% @user.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  </div>
<% end %>

	<div class="field">
		<%= f.label :Name %>
    	<%= f.text_field :name %>
	</div>

	<div class="field">
		<%= f.label :Image %>
		<%= f.attachment_field :profile_image %>
	</div>

	<div class="field">
		<%= f.label :Introduction %>
    	<%= f.text_area :introduction %>
	</div>

		<%= f.submit 'Update User' %>

<% end %>
</div>

app/views/users/index.html.erb
<div class="row">
<%= render 'users/list', user: @user, book: @book %>

<div class="col-xs-9">
<h2>Users</h2>
  <table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <th>
        <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg' %>
      </th>
      <th>
        <%= user.name %>
      </th>
      <th><%= link_to"show",user_path(user.id) %></th>
    </tr>
    <% end %>
  </tbody>
  </table>
</div>
</div>

app/views/users/show.html.erb
<%= render 'users/list', user: @user, book: @book %>

<div class="col-xs-9">
    <h2>Books</h2>

  <table class="table table-hover table-inverse">
  <thead>
    <tr> 
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
    <tr>
      <td>
        <%= link_to user_path(book.user) do %>
        <%= attachment_image_tag book.user, :profile_image, :fill, 100, 100, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg"%>
        <% end %>
      </td>
      <td>
        <%= link_to book.title, book_path(book) %>
      </td>
      <td>
        <%= book.body %>
      </td>
    </tr>
    <% end %>
  </tbody>
  </table>
</div>